---
# This recipe downloads galaxy, setup python virtualenv and create the galaxy.ini file

- name: Get Galaxy
  git:
    repo: 'https://github.com/galaxyproject/galaxy.git'
    clone: yes
    dest: '{{ galaxy_install_path }}'
    version: '{{ GALAXY_VERSION }}'

- name: Support for older version with ini configuration file
  set_fact:
    galaxy_config_file: '{{ galaxy_config_path }}/galaxy.ini'
  when: galaxy_version_number < 18.01

- name: Create galaxy configuration file
  copy:
    src: '{{ galaxy_config_file }}.sample'
    dest: '{{ galaxy_config_file }}'
    remote_src: true 

- name: Install Galaxy dependencies
  shell: './scripts/common_startup.sh >> {{ galaxy_log_path }}/galaxy_common_startup.log'
  args:
    chdir: '{{ galaxy_install_path }}'

- name: Set Virtualenv
  blockinfile:
    dest: '/home/{{ galaxy_user }}/.bashrc'
    marker: ''
    insertafter: EOF
    state: present
    content: |
      # Source Galaxy virutalenv
      source {{ galaxy_venv_path }}/bin/activate
