---
# This recipe downloads galaxy, setup python virtualenv and create the galaxy.ini file

- name: Get Galaxy
  git:
    repo: 'https://github.com/galaxyproject/galaxy.git'
    clone: yes
    dest: '{{ galaxy_install_path }}'
    version: '{{ GALAXY_VERSION }}'

- name: Create galaxy.ini file
  copy:
    src: '{{ galaxy_config_path }}/galaxy.ini.sample'
    dest: '{{ galaxy_config_path }}/galaxy.ini'
    remote_src: true 

- name: Install Galaxy dependencies
  shell: './scripts/common_startup.sh >> {{ galaxy_log_path }}/galaxy_common_startup.log'
  args:
    chdir: '{{ galaxy_install_path }}'

- name: Set Virtualenv
  lineinfile:
    dest: '/home/{{galaxy_user}}/.bashrc'
    line: '\n#source Virutalenv\nsource {{galaxy_venv_path}}/bin/activate'
    state: present
