---
# This recipe downloads galaxy, setup python virtualenv and create the galaxy.ini file

- name: Get Galaxy
  git:
    repo: 'https://github.com/galaxyproject/galaxy.git'
    clone: yes
    dest: '{{ galaxy_install_path }}'
    version: '{{ GALAXY_VERSION }}'

#______________________________________
# support for older galaxy versione (<18.01) when ini file was used

- name: Get Galaxy version number only for comparison
  set_fact:
    galaxy_version_number: "{{ GALAXY_VERSION | replace('release_','') }}"
  when: (GALAXY_VERSION != 'master') or (GALAXY_VERSION != 'dev')

- debug:
    msg: 'Galaxy version: {{ GALAXY_VERSION }}'
  when: (enable_debug_msg|bool)

- debug:
    msg: 'Galaxy version number: {{ galaxy_version_number }}'
  when: (enable_debug_msg|bool) and (galaxy_version_number is defined)

- name: Support for older version with ini configuration file
  set_fact:
    galaxy_config_file: '{{ galaxy_config_path }}/galaxy.ini'
  when: (galaxy_version_number is defined) and (galaxy_version_number|float < 18.01)

- name: Create galaxy configuration file
  copy:
    src: '{{ galaxy_config_file }}.sample'
    dest: '{{ galaxy_config_file }}'
    remote_src: true 

- name: Install Galaxy dependencies
  shell: './scripts/common_startup.sh >> {{ galaxy_log_path }}/galaxy_common_startup.log'
  args:
    chdir: '{{ galaxy_install_path }}'

- name: Set Virtualenv
  blockinfile:
    dest: '/home/{{ galaxy_user }}/.bashrc'
    marker: ''
    insertafter: EOF
    state: present
    content: |
      # Source Galaxy virutalenv
      source {{ galaxy_venv_path }}/bin/activate

#______________________________________
# Add python script to edit galaxy yaml configuration file
- name: Get python script to configure galaxy.yml
  get_url:
    url: 'https://raw.githubusercontent.com/Laniakea-elixir-it/Scripts/master/python/parse_galaxy_yaml.py'
    dest: '{{ galaxy_custom_script_path }}'
    mode: a+x
  become_user: root
  become_method: sudo
