---
# Prerequisites installation recipe
# Install CentOS 7 and Ubuntu 14.04 dependencies, creates directories, logrotate and password generator installation.

#---
#CentOS 7

- name: Install CentOS7 packages
  yum: name={{item}}
       state=present
  with_items:
    - git
    - vim
    - wget
    - logrotate
  become_user: root
  become_method: sudo
  when: ansible_os_family == "RedHat"

#- name: Install the 'Development tools' package group
#  yum:
#    name: "@Development tools"
#    state: latest
#    update_cache: yes
#  become_user: root
#  become_method: sudo
#  when: ansible_os_family == "RedHat"

-  name: Install 'Development tools' group # This solve broken dependencies on docker indigodatacloud/centos-sshd
   command: 'yum groupinstall -y "Development tools" --skip-broken'
   become_user: root
   become_method: sudo
   when: ansible_os_family == "RedHat"

#---
# Ubuntu 14.04

- name: Install Ubuntu packages
  apt: name={{item}}
       state=present
  with_items:
    - apt-transport-https
    - software-properties-common
    - git
    - vim
    - wget
    - logrotate
    - build-essential
    - python-apt #needed by apt_repository ansible core module
  become_user: root
  become_method: sudo
  when: ansible_os_family == "Debian"

#---
# Install virtualenv using pip. This prevent the system to use old virtualenv

- name: Install Virtualenv package
  pip: name={{ item }} state=forcereinstall
  with_items:
    - virtualenv
  become_user: root
  become_method: sudo

#########################################################
# Create directories

- name: Create directories
  file: path={{ item }}
        state=directory
        owner={{galaxy_user}}
        group={{galaxy_user}}
  with_items:
    - '{{ galaxy_log_path }}'
    - '{{ export_dir }}'
    - '{{ refdata_dir }}'
    - '/etc/galaxy'
    - '{{ tool_deps_path }}'
  become_user: root
  become_method: sudo

#########################################################
# Configure Logrotate

- name: Copy logrotate configuration file
  template: src=logrotate.j2 dest=/etc/logrotate.d/galaxy
  become_user: root
  become_method: sudo


#########################################################
# Add python random password generator
- name: Copy pwd-generator.py to /usr/local/bin
  template: src=pwd_generator.j2 dest=/usr/local/bin/pwd-generator mode=a+x
  become_user: root
  become_method: sudo

