---
# Prerequisites installation recipe
# Install OS dependencies, creates directories, logrotate and password generator installation.
# Compatible with CentOS 7, Ubuntu 14.04

#______________________________________
# CentOS 7

- name: Install CentOS7 packages
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - git
    - vim
    - wget
    - logrotate
  become_user: root
  become_method: sudo
  when: ansible_os_family == "RedHat"

- name: Install the 'Development tools' package group
  yum:
    name: "@Development tools"
    state: latest
    skip_broken: yes # This solve broken dependencies on docker indigodatacloud/centos-sshd
    update_cache: yes
  become_user: root
  become_method: sudo
  when: ansible_os_family == "RedHat" and ansible_version >= "2.3.0.0"

-  name: Install Development tools group # This solve broken dependencies on docker indigodatacloud/centos-sshd
   command: 'yum groupinstall -y "Development tools" --skip-broken'
   become_user: root
   become_method: sudo
   when: ansible_os_family == "RedHat" and ansible_version < "2.3.0.0"

#______________________________________
# Ubuntu 14.04

- name: Install Ubuntu packages
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - apt-transport-https
    - software-properties-common
    - git
    - vim
    - wget
    - logrotate
    - build-essential
    - python-apt #needed by apt_repository ansible core module
  become_user: root
  become_method: sudo
  when: ansible_os_family == "Debian"

#______________________________________
# Install pip.
# This prevent to install different pip versions.

- name: Check pip
  command: 'pip --version'
  ignore_errors: true
  changed_when: false # read-only task
  check_mode: no
  register: pip_is_installed

- yum:
    name: 'python-pip'
    state: present
  become_user: root
  become_method: sudo
  when: ansible_os_family == "RedHat" and pip_is_installed.rc != 0

- apt:
    name: 'python-pip'
    state: present
  become_user: root
  become_method: sudo
  when: ansible_os_family == "Debian" and pip_is_installed.rc != 0

#______________________________________
# Install virtualenv using pip.
# This prevent the system to use old virtualenv.

- name: Install Virtualenv package
  pip:
    name: '{{ item }}'
    state: forcereinstall
  with_items:
    - virtualenv
  become_user: root
  become_method: sudo

#______________________________________
# Create directories

- set_fact:
    export_dir: /home/galaxy
    #when: galaxy_lrms == "slurm"
    #when: enable_storage_advanced_options|bool == false


- name: Create directories
  file:
    path: '{{ item }}'
    state: directory
    owner: '{{ galaxy_user }}'
    group: '{{ galaxy_user }}'
  with_items:
    - '{{ galaxy_log_path }}'
    - '{{ export_dir }}'
    - '/etc/galaxy'
    - '{{ tool_deps_path }}'
  become_user: root
  become_method: sudo

#______________________________________
# Configure Logrotate

- name: Copy logrotate configuration file
  template:
    src: 'logrotate.j2'
    dest: '/etc/logrotate.d/galaxy'
  become_user: root
  become_method: sudo

#______________________________________
# Add python random password generator
- name: Copy pwd-generator.py to /usr/local/bin
  template:
    src: 'pwd_generator.j2'
    dest: '/usr/local/bin/pwd-generator'
    mode: a+x
  become_user: root
  become_method: sudo
