---
# Proftpd installation and configuration recipe

#______________________________________-
# CentOS 7

- name: '[EL] Install proftpd'
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - proftpd
    - proftpd-postgresql
  become_user: root
  become_method: sudo
  when: ansible_os_family == "RedHat"

#______________________________________
# Ubuntu
# On Ubuntu Proftpd service is started by default after installation. It needs to be restarted after the configuration.

- name: '[Ubuntu] Install proftpd'
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - proftpd
    - proftpd-mod-pgsql
  become_user: root
  become_method: sudo
  when: ansible_os_family == "Debian"

#______________________________________
# Stop service before configuration

- name: Stop Proftpd server
  service:
    name: proftpd
    state: stopped
    enabled: no
  become_user: root
  become_method: sudo
  ignore_errors: yes

#______________________________________
# Cconfigure Proftpd

- name: Create proftpd db random passwd
  command: "{{ galaxy_custom_script_path }}/pwd-generator -l 20"
  register: proftpd_db_passwd

- name: Set proftpd configuration file path on Ubuntu
  set_fact:
    proftpd_conf_path: '/etc/proftpd/proftpd.conf'
  when: ansible_os_family == "Debian"

- name: Copy the proftpd configuration file
  template:
    src: 'proftpd.conf.j2'
    dest: '{{ proftpd_conf_path }}'
  become_user: root
  become_method: sudo

- name: Create proftpd db user
  postgresql_user:
    db: 'galaxy'
    name: '{{ proftpd_db_user }}'
    password: '{{ proftpd_db_passwd.stdout }}'
    priv: galaxy_user:ALL
  become_user: postgres
  become_method: sudo

- name: Set ip address | vm
  ini_file:
    dest: '{{ galaxy_config_file }}'
    section: 'app:main'
    option: 'ftp_upload_site'
    value: '{{ ansible_default_ipv4.address }}'
  when: ansible_virtualization_type != "docker"

- name: Set ip address | docker
  ini_file:
    dest: '{{ galaxy_config_file }}'
    section: 'app:main'
    option: ftp_upload_site
    value: "indigo-dc.galaxycloud docker by elixir-italy.org"
  when: ansible_virtualization_type == "docker"
