---
# Supervisord installation and configuration recipe

#______________________________________
# CentOS 7

- name: '[EL] Check and install Supervisor dependencies'
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - supervisor
  become_user: root
  become_method: sudo
  when: ansible_os_family == "RedHat"

- name: '[EL] Set supervisord conf path'
  set_fact:
    supervisord_conf_path: '/etc'
  when: ansible_os_family == "RedHat"

- name: '[EL] Copy supervisord configuration file'
  template:
    src: 'supervisord.conf.j2'
    dest: '/etc/supervisord.d/galaxy_web.ini'
  become_user: root
  become_method: sudo
  when: ansible_os_family == "RedHat"

#______________________________________
# Ubuntu
# On Ubuntu Supervisord service is started by default after installation. We need to reread and update the configuration.
# The service is stopped here and restarted using galaxy-startup script.

- name: '[Ubuntu] Check and install Supervisor dependencies'
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - python-meld3
    - supervisor
  become_user: root
  become_method: sudo
  when: ansible_os_family == "Debian"

- name: '[Ubuntu] Stop supervisor'
  service:
    name: supervisor
    state: stopped
  become_user: root
  become_method: sudo
  when: ansible_os_family == "Debian"

- name: '[Ubuntu] Set supervisord conf path'
  set_fact:
    supervisord_conf_path: '/etc/supervisor'
  when: ansible_os_family == "Debian"

- name: '[Ubuntu] Copy supervisord configuration file'
  template:
    src: 'supervisord.conf.j2'
    dest: '/etc/supervisor/conf.d/galaxy_web.conf'
  become_user: root
  become_method: sudo
  when: ansible_os_family == "Debian"
