---
# uWSGI installation and configuration recipe

#______________________________________
# CentOS 7

- name: '[EL] Check and install uWSGI dependencies'
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - python
    - python-devel
  become_user: root
  become_method: sudo
  when: ansible_os_family == "RedHat"

#______________________________________
# Ubuntu 14.04
- name: '[Ubuntu] Check and install uWSGI dependencies'
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - python
    - python-dev
  become_user: root
  become_method: sudo
  when: ansible_os_family == "Debian"

#______________________________________
# Install uWSGI

- name: Include uWSGI specific variables.
  include_vars: uwsgi_vars.yml

- name: Install uWSGI for galaxy
  pip:
    name: uwsgi
    virtualenv: "{{ galaxy_venv_path }}"
    virtualenv_command: "{{ pip_virtualenv_command | default( 'virtualenv' ) }}"
    #extra_args: "--extra-index-url https://wheels.galaxyproject.org/"

#______________________________________
# Add uWSGI section to galaxy.ini file

- name: Copy uwsgi section to galaxy.ini
  template:
    src: 'uwsgi.ini.j2'
    dest: '/tmp/uwsgi.ini.sample'

- name: Copy uwsgi section to galaxy.ini
  shell: 'cat /tmp/uwsgi.ini.sample >> {{ galaxy_config_file }}'

- name: uWSGI section config
  ini_file:
    dest: '{{ galaxy_config_file }}'
    section: '{{ item.section }}'
    option: '{{ item.option }}'
    value: '{{ item.value }}'
  with_items:
    - { section: 'uwsgi', option: 'master', value: 'True' }
    - { section: 'uwsgi', option: 'processes', value: '{{ uwsgi_processes }}' }
    - { section: 'uwsgi', option: 'socket', value: '{{ uwsgi_socket_port }}' }
    - { section: 'uwsgi', option: 'stats', value: '{{ uwsgi_stats_port }}' }
    - { section: 'uwsgi', option: 'pythonpath', value: '{{ galaxy_install_path }}/lib' }
    - { section: 'uwsgi', option: 'pythonhome', value: '{{ galaxy_venv_path }}' }
    - { section: 'uwsgi', option: 'threads', value: '{{ uwsgi_threads }}' }
    - { section: 'uwsgi', option: 'logto', value: '{{ uwsgi_errorlog }}' }
    - { section: 'uwsgi', option: 'no-orphans', value: 'True' }
    - { section: 'uwsgi', option: 'buffer-size', value: '{{ uwsgi_buffer_size }}' }

- name: uWSGI options for performance and robustness
  ini_file:
    dest: '{{ galaxy_config_file }}'
    section: '{{ item.section }}'
    option: '{{ item.option }}'
    value: '{{ item.value }}'
  with_items:
    - { section: 'uwsgi', option: 'single-interpreter', value: '{{ uwsgi_single_interpreter }}' }
    - { section: 'uwsgi', option: 'thunder-lock', value: '{{ uwsgi_thunder_lock }}' }
    - { section: 'uwsgi', option: 'harakiri', value: '{{ uwsgi_harakiri_value }}' }
  when: enable_robustness_features|bool

- name: '[VM] Set at least 2 uWSGI wn if proc<=2'
  ini_file:
    dest: '{{ galaxy_config_file }}'
    section: 'uwsgi'
    option: 'processes'
    value: '2'
  when: ansible_processor_vcpus <= 2

- name: '[VM] Set 8 uWSGI wn if proc>8'
  ini_file:
    dest: '{{ galaxy_config_file }}'
    section: 'uwsgi'
    option: 'processes'
    value: '8'
  when: ansible_processor_vcpus > 8

- name: '[Docker] Force processes to 2 on Docker for automated build' 
  ini_file:
    dest: '{{ galaxy_config_file }}'
    section: 'uwsgi'
    option: 'processes'
    value: '2'
  when: ansible_virtualization_type == "docker"

#______________________________________
# Edit galaxy.ini file

- name: Edit galaxy.ini
  ini_file:
    dest: '{{ galaxy_config_file }}'
    section: '{{ item.section }}'
    option: '{{ item.option }}'
    value: ' {{item.value }}'
  with_items:
    - { section: 'app:main', option: 'static_enabled', value: 'False' }
    - { section: 'app:main', option: 'track_jobs_in_database', value: 'True' } # The track_jobs_in_database option in galaxy.ini can still be set but should be unnecessary. If there are more than one [server:...] sections in the file, database job tracking will be enabled automatically.

#______________________________________
# job_conf section
# Local runner configuration
# https://wiki.galaxyproject.org/Admin/Config/Performance/Cluster

- name: if proc==4
  set_fact:
    galaxy_workers: "4"
    galaxy_local_slos: "2"
    galaxy_registered_concurrent_jobs: "2"
  when: ansible_processor_vcpus == "4"

- name: if proc==8
  set_fact: 
    galaxy_workers: "8"
    galaxy_local_slos: "2"
    galaxy_registered_concurrent_jobs: "2"
  when: ansible_processor_vcpus == "8"

- name: if proc==16
  set_fact: 
    galaxy_workers: "16"
    galaxy_local_slos: "4"
    galaxy_registered_concurrent_jobs: "2"
  when: ansible_processor_vcpus == "16"

- name: if proc==32
  set_fact: 
    galaxy_workers: "32"
    galaxy_local_slos: "4"
    galaxy_registered_concurrent_jobs: "4"
  when: ansible_processor_vcpus == "32"

- name: if proc==64
  set_fact: 
    galaxy_workers: "64"
    galaxy_local_slos: "4"
    galaxy_registered_concurrent_jobs: "4"
  when: ansible_processor_vcpus == "64"

- name: Copy job_conf configration file
  template:
    src: 'job_conf.xml.j2'
    dest: '{{ galaxy_config_path }}/job_conf.xml'
