---
# uWSGI installation and configuration recipe

#---
# CentOS 7
- name: Check and install uWSGI dependencies on CentOS7
  yum: name={{item}}
       state=present
  with_items:
    - python
    - python-devel
  become_user: root
  become_method: sudo
  when: ansible_os_family == "RedHat"

#---
# Ubuntu 14.04
- name: Check and install uWSGI dependencies on Ubuntu
  apt: name={{item}}
       state=present
  with_items:
    - python
    - python-dev
  become_user: root
  become_method: sudo
  when: ansible_os_family == "Debian"

#########################################################
# Install uWSGI

- name: Include uWSGI specific variables.
  include_vars: uwsgi_vars.yml

- name: Install uWSGI
  pip: name=uwsgi
       virtualenv="{{galaxy_venv_path}}"

#---
# Add uWSGI section to galaxy.ini file

- name: Add uWSGI section
  blockinfile:
    dest: "{{galaxy_config_file}}"
    marker: ""
    content: |
      #
      # ---- uWSGI -------------------------------------------------------------------------
      # https://wiki.galaxyproject.org/Admin/Config/Performance/Scaling
      #

- name: uWSGI section config
  ini_file: dest={{galaxy_config_file}} section={{item.section}} option={{item.option}} value={{item.value}}
  with_items:
    - { section: 'uwsgi', option: 'master', value: 'True' }
    - { section: 'uwsgi', option: 'processes', value: '{{uwsgi_processes}}' }
    - { section: 'uwsgi', option: 'socket', value: '{{uwsgi_socket_port}}' }
    - { section: 'uwsgi', option: 'stats', value: '{{uwsgi_stats_port}}' }
    - { section: 'uwsgi', option: 'pythonpath', value: '{{galaxy_install_path}}/lib' }
    - { section: 'uwsgi', option: 'pythonhome', value: '{{galaxy_venv_path}}' }
    - { section: 'uwsgi', option: 'threads', value: '{{uwsgi_threads}}' }
    - { section: 'uwsgi', option: 'logto', value: '{{uwsgi_errorlog}}' }
    - { section: 'uwsgi', option: 'pidfile', value: '{{ uwsgi_pidfile }}' }

- name: if proc==1
  ini_file: dest={{galaxy_config_file}}
            section=uwsgi
            option=processes
            value=1
  when: ({{ansible_processor_vcpus}} == 1)

- name: if proc>8
  ini_file: dest={{galaxy_config_file}}
            section=uwsgi
            option=processes
            value=8
  when: ({{ansible_processor_vcpus}} > 8)

#---
# Edit galaxy.ini file

- name: Edit galaxy.ini
  ini_file: dest={{galaxy_config_file}} section={{item.section}} option={{item.option}} value="{{item.value}}"
  with_items:
    - { section: 'app:main', option: 'static_enabled', value: 'False' }
    - { section: 'app:main', option: 'track_jobs_in_database', value: 'True' } # The track_jobs_in_database option in galaxy.ini can still be set but should be unnecessary. If there are more than one [server:...] sections in the file, database job tracking will be enabled automatically.

#########################################################
# job_conf section

#---
# Local runner configuration
# https://wiki.galaxyproject.org/Admin/Config/Performance/Cluster

- name: if proc==4
  set_fact:
    galaxy_workers: "4"
    galaxy_local_slos: "2"
    galaxy_registered_concurrent_jobs: "2"
  when: ({{ansible_processor_vcpus}} == 4)

- name: if proc==8
  set_fact: 
    galaxy_workers: "8"
    galaxy_local_slos: "4"
    galaxy_registered_concurrent_jobs: "2"
  when: ({{ansible_processor_vcpus}} == 8)

- name: if proc==16
  set_fact: 
    galaxy_workers: "16"
    galaxy_local_slos: "4"
    galaxy_registered_concurrent_jobs: "4"
  when: ({{ansible_processor_vcpus}} == 16)

- name: if proc==32
  set_fact: 
    galaxy_workers: "32"
    galaxy_local_slos: "8"
    galaxy_registered_concurrent_jobs: "4"
  when: ({{ansible_processor_vcpus}} == 32)

- name: if proc==64
  set_fact: 
    galaxy_workers: "64"
    galaxy_local_slos: "8"
    galaxy_registered_concurrent_jobs: "8"
  when: ({{ansible_processor_vcpus}} == 64)

- name: Copy job_conf configration file
  template: src=job_conf.xml.j2 dest={{galaxy_config_path}}/job_conf.xml

#---
# Job configuration - 6 job handlers

- name: Add server handler 0
  ini_file: dest={{galaxy_config_file}} section={{item.section}} option={{item.option}} value={{item.value}}
  with_items: 
    - { section: 'server:handler0', option: 'use', value: 'egg:Paste@http' }
    - { section: 'server:handler0', option: 'port', value: '8090' }
    - { section: 'server:handler0', option: 'host', value: '127.0.0.1' }
    - { section: 'server:handler0', option: 'use_threadpool', value: 'true' }
    - { section: 'server:handler0', option: 'threadpool_workers', value: '5' }
#---
- name: Add server handler 1
  ini_file: dest={{galaxy_config_file}} section={{item.section}} option={{item.option}} value={{item.value}}
  with_items: 
    - { section: 'server:handler1', option: 'use', value: 'egg:Paste@http' }
    - { section: 'server:handler1', option: 'port', value: '8091' }
    - { section: 'server:handler1', option: 'host', value: '127.0.0.1' }
    - { section: 'server:handler1', option: 'use_threadpool', value: 'true' }
    - { section: 'server:handler1', option: 'threadpool_workers', value: '5' }
#---
- name: Add server handler 2
  ini_file: dest={{galaxy_config_file}} section={{item.section}} option={{item.option}} value={{item.value}}
  with_items: 
    - { section: 'server:handler2', option: 'use', value: 'egg:Paste@http' }
    - { section: 'server:handler2', option: 'port', value: '8092' }
    - { section: 'server:handler2', option: 'host', value: '127.0.0.1' }
    - { section: 'server:handler2', option: 'use_threadpool', value: 'true' }
    - { section: 'server:handler2', option: 'threadpool_workers', value: '5' }
#---
- name: Add server handler 3
  ini_file: dest={{galaxy_config_file}} section={{item.section}} option={{item.option}} value={{item.value}}
  with_items: 
    - { section: 'server:handler3', option: 'use', value: 'egg:Paste@http' }
    - { section: 'server:handler3', option: 'port', value: '8093' }
    - { section: 'server:handler3', option: 'host', value: '127.0.0.1' }
    - { section: 'server:handler3', option: 'use_threadpool', value: 'true' }
    - { section: 'server:handler3', option: 'threadpool_workers', value: '5' }
#---
- name: Add server handler 4
  ini_file: dest={{galaxy_config_file}} section={{item.section}} option={{item.option}} value={{item.value}}
  with_items: 
    - { section: 'server:handler4', option: 'use', value: 'egg:Paste@http' }
    - { section: 'server:handler4', option: 'port', value: '8094' }
    - { section: 'server:handler4', option: 'host', value: '127.0.0.1' }
    - { section: 'server:handler4', option: 'use_threadpool', value: 'true' }
    - { section: 'server:handler4', option: 'threadpool_workers', value: '5' }
#---
- name: Add server handler 5
  ini_file: dest={{galaxy_config_file}} section={{item.section}} option={{item.option}} value={{item.value}}
  with_items: 
    - { section: 'server:handler5', option: 'use', value: 'egg:Paste@http' }
    - { section: 'server:handler5', option: 'port', value: '8095' }
    - { section: 'server:handler5', option: 'host', value: '127.0.0.1' }
    - { section: 'server:handler5', option: 'use_threadpool', value: 'true' }
    - { section: 'server:handler5', option: 'threadpool_workers', value: '5' }
